### ISSUE TITLE
Mini ToDo list

### ISSUE THREAD

**Issue by capoaira** [capoaira/liga-tabelle#46]
- [x] Spieltag erstellen: Grammatik 
- [x] Hinweis "Noch kein Spieltag erstellt" ausrichten.
- [x] buttons min-height 
- [x] Hinweise bei Liga Seite (keine Liga erstellt)
- [ ] Link bei Ligenübersicht nicht von Ersteller-Link beeinflussen lassen
- [x] Vereine in Liga und Spieltagesübersicht verlinken
- [x] DateTime erst nach auswahl des Spieltages anzeigen
- [x] aside inhalt finden oder löschen
- [ ] vereinslogo/ligalogo löschen
- [x] eindeutige Titel für Seiten
- [x] Title für alle Buttons

**Comment by Chris-2001** [comment]
> * [ ]  Spieltag erstellen: Grammatik
> * [ ]  Hinweis "Noch kein Spieltag erstellt" ausrichten.
> * [ ]  buttons min-height
> * [ ]  Hinweise bei Liga Seite (keine Liga erstellt)
> * [ ]  Link bei Ligenübersicht nicht von Ersteller-Link beeinflussen lassen
> * [ ]  Vereine in Liga und Spieltagesübersicht verlinken
> * [ ]  Daten des 2. Spieltages
> * [ ]  DateTime erst nach auswahl des Spieltages anzeigen
> * [ ]  aside inhalt finden oder löschen
> * [ ]  vereinslogo löschen

**Comment by Chris-2001** [comment]
Ups

**Comment by capoaira** [comment]
Test-- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.
